/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cijzyroxxjggitpvvolx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpanp5cm94eGpnZ2l0cHZ2b2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxMjgwNDYsImV4cCI6MjA4ODcwNDA0Nn0.3p4aOyVSQRyZtPF-W7aUbKrf7iUGk5a_eL-kUh9MmdY"